name: Reset Daily Views

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  reset-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Daily View Counter
        run: |
          # Mengemaskini kaunter harian ke 0 pada jam 12 AM MYT
          echo "Daily counter reset to 0 at 12:00 AM MYT"
